import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import { createHmac } from "node:crypto";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Verify user authentication
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      console.error('No authorization header provided');
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!;
    
    // User client for auth verification
    const userSupabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } }
    });

    const { data: { user }, error: authError } = await userSupabase.auth.getUser();
    if (authError || !user) {
      console.error('Auth error:', authError?.message);
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Service client for updating order (bypasses RLS)
    const serviceSupabase = createClient(supabaseUrl, supabaseServiceKey);

    const { dbOrderId, razorpayOrderId, razorpayPaymentId, razorpaySignature } = await req.json();
    
    if (!dbOrderId || !razorpayOrderId || !razorpayPaymentId || !razorpaySignature) {
      console.error('Missing required fields');
      return new Response(JSON.stringify({ error: 'Missing required payment details' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Verifying payment for order:', dbOrderId, 'Razorpay order:', razorpayOrderId);

    // Verify the order belongs to the authenticated user
    const { data: order, error: orderError } = await userSupabase
      .from('orders')
      .select('id, total_amount, user_id, payment_status')
      .eq('id', dbOrderId)
      .eq('user_id', user.id)
      .single();

    if (orderError || !order) {
      console.error('Order not found or unauthorized:', orderError?.message);
      return new Response(JSON.stringify({ error: 'Order not found' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Check if already paid
    if (order.payment_status === 'paid') {
      console.log('Order already marked as paid');
      return new Response(JSON.stringify({ success: true, message: 'Payment already verified' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const keyId = Deno.env.get('RAZORPAY_KEY_ID');
    const keySecret = Deno.env.get('RAZORPAY_KEY_SECRET');

    if (!keyId || !keySecret) {
      console.error('Razorpay credentials not configured');
      throw new Error('Payment system not configured');
    }

    // Step 1: Verify Razorpay signature
    // The signature is generated by Razorpay using: order_id|payment_id
    const expectedSignature = createHmac('sha256', keySecret)
      .update(`${razorpayOrderId}|${razorpayPaymentId}`)
      .digest('hex');

    if (expectedSignature !== razorpaySignature) {
      console.error('Invalid payment signature');
      return new Response(JSON.stringify({ error: 'Invalid payment signature' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Signature verified, checking payment status with Razorpay API');

    // Step 2: Verify payment status with Razorpay API
    const paymentResponse = await fetch(
      `https://api.razorpay.com/v1/payments/${razorpayPaymentId}`,
      {
        headers: {
          'Authorization': 'Basic ' + btoa(`${keyId}:${keySecret}`),
        },
      }
    );

    if (!paymentResponse.ok) {
      const errorText = await paymentResponse.text();
      console.error('Razorpay API error:', errorText);
      return new Response(JSON.stringify({ error: 'Failed to verify payment with Razorpay' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const payment = await paymentResponse.json();
    console.log('Razorpay payment status:', payment.status);

    // Verify payment is captured and amount matches
    if (payment.status !== 'captured') {
      console.error('Payment not captured, status:', payment.status);
      return new Response(JSON.stringify({ error: `Payment not completed. Status: ${payment.status}` }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Verify amount matches (Razorpay amount is in paise)
    const expectedAmount = Math.round(Number(order.total_amount) * 100);
    if (payment.amount !== expectedAmount) {
      console.error('Amount mismatch:', payment.amount, 'vs', expectedAmount);
      return new Response(JSON.stringify({ error: 'Payment amount mismatch' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Step 3: Update order payment status using service role
    const { error: updateError } = await serviceSupabase
      .from('orders')
      .update({ 
        payment_status: 'paid',
        updated_at: new Date().toISOString()
      })
      .eq('id', dbOrderId);

    if (updateError) {
      console.error('Failed to update order:', updateError.message);
      return new Response(JSON.stringify({ error: 'Failed to update order status' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Payment verified and order updated successfully');

    return new Response(JSON.stringify({ 
      success: true, 
      message: 'Payment verified successfully'
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error('Error verifying payment:', error);
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
