import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import { createHmac, timingSafeEqual } from "node:crypto";

// CORS headers - permissive to support various preview and production environments
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

// Constant-time string comparison to prevent timing attacks
function secureCompare(a: string, b: string): boolean {
  try {
    // Convert hex strings to Uint8Array
    const hexToBytes = (hex: string): Uint8Array => {
      const bytes = new Uint8Array(hex.length / 2);
      for (let i = 0; i < hex.length; i += 2) {
        bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
      }
      return bytes;
    };
    
    const bufferA = hexToBytes(a);
    const bufferB = hexToBytes(b);
    
    if (bufferA.length !== bufferB.length) {
      return false;
    }
    
    return timingSafeEqual(bufferA, bufferB);
  } catch {
    return false;
  }
}

serve(async (req) => {
  // Handle CORS preflight requests
  
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Verify user authentication
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      console.error('No authorization header provided');
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!;
    
    // User client for auth verification
    const userSupabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } }
    });

    const { data: { user }, error: authError } = await userSupabase.auth.getUser();
    if (authError || !user) {
      console.error('Auth error:', authError?.message);
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Service client for updating order (bypasses RLS)
    const serviceSupabase = createClient(supabaseUrl, supabaseServiceKey);

    const { dbOrderId, razorpayOrderId, razorpayPaymentId, razorpaySignature } = await req.json();
    
    if (!dbOrderId || !razorpayOrderId || !razorpayPaymentId || !razorpaySignature) {
      console.error('Missing required fields');
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Verifying payment for order:', dbOrderId, 'Razorpay order:', razorpayOrderId);

    // Verify the order belongs to the authenticated user
    const { data: order, error: orderError } = await userSupabase
      .from('orders')
      .select('id, total_amount, user_id, payment_status')
      .eq('id', dbOrderId)
      .eq('user_id', user.id)
      .single();

    if (orderError || !order) {
      console.error('Order verification failed:', { orderId: dbOrderId, userId: user.id, error: orderError?.message });
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Check if already paid
    if (order.payment_status === 'paid') {
      console.log('Order already marked as paid');
      return new Response(JSON.stringify({ success: true, message: 'Payment already verified' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const keyId = Deno.env.get('RAZORPAY_KEY_ID');
    const keySecret = Deno.env.get('RAZORPAY_KEY_SECRET');

    if (!keyId || !keySecret) {
      console.error('Razorpay credentials not configured');
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Step 1: Verify Razorpay signature using constant-time comparison
    // The signature is generated by Razorpay using: order_id|payment_id
    const expectedSignature = createHmac('sha256', keySecret)
      .update(`${razorpayOrderId}|${razorpayPaymentId}`)
      .digest('hex');

    if (!secureCompare(expectedSignature, razorpaySignature)) {
      console.error('Signature verification failed', { orderId: dbOrderId });
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Signature verified, checking payment status with Razorpay API');

    // Step 2: Verify payment status with Razorpay API
    const paymentResponse = await fetch(
      `https://api.razorpay.com/v1/payments/${razorpayPaymentId}`,
      {
        headers: {
          'Authorization': 'Basic ' + btoa(`${keyId}:${keySecret}`),
        },
      }
    );

    if (!paymentResponse.ok) {
      const errorText = await paymentResponse.text();
      console.error('Razorpay API error:', { orderId: dbOrderId, error: errorText });
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const payment = await paymentResponse.json();
    console.log('Razorpay payment status:', payment.status);

    // Verify payment is captured and amount matches
    if (payment.status !== 'captured') {
      console.error('Payment not captured', { orderId: dbOrderId, status: payment.status });
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Verify amount matches (Razorpay amount is in paise)
    const expectedAmount = Math.round(Number(order.total_amount) * 100);
    if (payment.amount !== expectedAmount) {
      console.error('Amount mismatch', { orderId: dbOrderId, expected: expectedAmount, received: payment.amount });
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Step 3: Update order payment status using service role
    const { error: updateError } = await serviceSupabase
      .from('orders')
      .update({ 
        payment_status: 'paid',
        updated_at: new Date().toISOString()
      })
      .eq('id', dbOrderId);

    if (updateError) {
      console.error('Failed to update order:', { orderId: dbOrderId, error: updateError.message });
      return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Payment verified and order updated successfully');

    return new Response(JSON.stringify({ 
      success: true, 
      message: 'Payment verified successfully'
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error('Error verifying payment:', errorMessage);
    return new Response(JSON.stringify({ error: 'Payment verification failed' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
